config/routes.rb
Rails.application.routes.draw do
  root 'site#bio'
  
  get '/show', to: 'site#show'
  get '/bio', to: 'site#bio'
  get '/cv', to: 'site#cv'
  get '/blog', to: 'blog#index'
  get '/github', to: 'site#github'
  get '/sandbox', to: 'site#sandbox'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :active_class

  def active_class
    @active = Hash.new { '' }
    @active[params[:action].to_sym] = 'active'
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

  def index

  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog/index.html.haml
.header-img.orange
  %h2.title Blog Posts
%hr
.card.text
  %p There is nothing here.

app/views/cinemagraphs/_forest.html.haml
.card.cinemagraph
  %svg#forest
    %radialGradient#firefly_light{ cx: '50%', cy: '50%', fx: '50%', fy: '50%', r: '50%'}
      %stop{ offset: '0%', 'stop-color' => 'rgb(255,255,195)', 'stop-opacity' => '1'}
      %stop{ offset: '100%', :style => 'stop-color: rgb(255,255,155);stop-opacity:0;'}

    %radialGradient#sunbeam{ cx: '40%', cy: '50%', fx: '10%', fy: '20%', r: '50%'}
      %stop{ offset: '0%', 'stop-color' => 'rgb(255,255,215)', 'stop-opacity' => '0.8'}
      %stop{ offset: '100%', 'stop-color' => 'rgb(255,255,175)', 'stop-opacity' => '0'}

    %radialGradient#ambient_glow{ cx: '50%', cy: '50%', fx: '55%', fy: '35%', r: '50%'}
      %stop{ offset: '0%', 'stop-color' => 'rgb(255,255,215)', 'stop-opacity' => '1'}
      %stop{ offset: '30%', 'stop-color' => 'rgb(255,255,215)', 'stop-opacity' => '0.5'}
      %stop{ offset: '100%', 'stop-color' => 'rgb(255,255,175)', 'stop-opacity' => '0'}

    %radialGradient#darkness{ cx: '50%', cy: '50%', fx: '50%', fy: '50%', r: '50%'}
      %stop{ offset: '0%', 'stop-color' => 'rgb(0,0,20)', 'stop-opacity' => '0.8'}
      %stop{ offset: '100%', 'stop-color' => 'rgb(0,0,20)', 'stop-opacity' => '0.2'}

    %polygon#sunray{ fill: 'url(#sunbeam)', opacity: '1', :points => '175,80 180,80 225,250 175,250'}
    %ellipse#sunspot{ cx: '200', cy: '230', fill: 'url(#firefly_light)', opacity: '0.3', rx: '45', ry: '30'}
    %ellipse#nighttime{ cx: '50%', cy: '50%', fill: 'url(#darkness)', opacity: '1', rx: '100%', ry: '100%'}
    %ellipse#ambient{ cx: '20%', cy: '50%', fill: 'url(#ambient_glow)', opacity: '0.4', rx: '100%', ry: '50%'}
    
  %h3 Forest

app/views/cinemagraphs/_mountain.html.haml
.card.cinemagraph
  %svg#mountain
    %radialGradient#northern_lights{ cx: '50%', cy: '50%', fx: '50%', fy: '40%', r: '50%'}
      %stop{ offset: '0%', 'stop-color' => 'rgb(0, 255, 0)', 'stop-opacity' => '1'}
      %stop{ offset: '100%', 'stop-color' => 'rgb(150,255,20)', 'stop-opacity' => '0'}
    %radialGradient#smoke{ cx: '50%', cy: '50%', fx: '50%', fy: '50%', r: '50%'}
      %stop{ offset: '0%', 'stop-color' => 'rgb(200,200,200)', 'stop-opacity' => '0.6'}
      %stop{ offset: '100%', 'stop-color' => 'rgb(200,200,200)', 'stop-opacity' => '0'}
    / %ellipse{ cx: '50%', cy: '50%', fill: 'url(#northern_lights)', opacity: '1', rx: '2.5%', ry: '25%'}
    %circle{ cx: 'calc(100% - 50px)', cy: '215', fill: 'url(#smoke)', r: '10px'}
  %h3 Mountain

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title PersonalSite
    %link{ href: 'https://fonts.googleapis.com/css?family=Raleway:300', rel: 'stylesheet', type: 'text/css' }
    %meta{content: 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0', name: 'viewport'}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.site-menu
      .logo
      %h1 JoeKle.men
      %ul
        %li{ class: @active[:bio] }
          = link_to 'Bio', bio_path
        %li{ class: @active[:blog] }
          = link_to 'Blog', blog_path
        %li{ class: @active[:cv] }
          = link_to 'CV', cv_path
        %li{ class: @active[:github] }
          = link_to 'GitHub', github_path
        %li{ class: @active[:seo] }
          = link_to 'Sandbox', sandbox_path
      .hamburger ☰
    .content
      = yield

app/views/site/bio.html.haml
.row
  .header-img.red
    %h2.title About Me
.row
  .card.col-xs-4
    .hidden-xs
      = fa_icon 'github'
      = link_to 'GitHub', 'https://www.github.com/ncultimate'
    .visible-xs
      = link_to fa_icon('github'), 'https://www.github.com/ncultimate'
  .card.col-xs-4
    .hidden-xs
      = fa_icon 'twitter'
      = link_to 'Twitter', 'https://twitter.com/hi_jklmn'
    .visible-xs
      = link_to fa_icon('twitter'), 'https://twitter.com/hi_jklmn'
  .card.col-xs-4
    .hidden-xs
      = fa_icon 'linkedin'
      = link_to 'LinkedIn', 'https://www.linkedin.com/in/joseph-klemen-450a8480'
    .visible-xs
      = link_to fa_icon('linkedin'), 'https://www.linkedin.com/in/joseph-klemen-450a8480'
.row
  .card.me.col-xs-3.col-md-2
    = image_tag 'me'
  .card.title.col-xs-9.col-md-10
    %h1 Joseph M. Klemen
    %h2 Front-end Developer
    %p Purdue University, Class of 2015
    %p MS, BS - Computer Science
%hr
.row.icon-text
  .col-sm-8.col-xs-12.text
    %h4 Programming Interests
    %ul
      %li CSS Animations, SVG libraries, and other methods of web visualization.
      %li Writing DSLs with Yacc/Bison and Lex/Flex, especially ones that serve a very specific useless purpose.
      %li Code Golfing and Regex Golfing. I enjoy the challenge of writing perversely short code for the sake of competition.
  .col-sm-4.hidden-xs.icon
    = fa_icon 'code'
%hr
.row.icon-text
  .col-sm-4.hidden-xs.icon
    = fa_icon 'bicycle'
  .col-sm-8.col-xs-12.text
    %h4 Hobbies
    %ul
      %li Movies and Video Games. Speed running through indie horror games is always a good time.
      %li Running, Biking, Disc Golf and Ultimate Frisbee. Nothing cleanses the soul like throwing a frisbee as hard or as far as you can.
      %li Board Games of all varieties. Betrayal at House on the Hill and Sentinels of the Multiverse are my favorites.
%hr
.row.icon-text
  .col-sm-8.col-xs-12.text
    %h4 Academic Interests
    %ul
      %li Pretty much any proceeding of the International Conference on Fun with Algorithms.
      %li Compilers, Parsers, Lexers, and everything in between. 
      %li Code analysis techniques such as Dynamic Slicing, Symbolic Execution, Profiling, and Test Generation. 
  .col-sm-4.hidden-xs.icon
    = fa_icon 'graduation-cap'
%hr
%footer

app/views/site/cv.html.haml
.header-img.blue
  %h2.title Curriculum Vitae
%hr
.card.text
  %p There is nothing here.

app/views/site/github.html.haml
.header-img.red
  %h2.title My GitHub Projects
%hr
.card.text
  %p There is nothing here.

app/views/site/sandbox.html.haml
.header-img.green
  %h2.title Programming Sandbox
%hr
.card.text
  %p This page is an experimental area of sorts for animations, apps, and everything in between that needed a home. 

.card.img.col-sm-4
  %a{ href: 'http://loading-css.herokuapp.com/', target: '_blank' }
    = image_tag 'css_loaders'
    %h3 Load Wow
    %p A handful of single-element loading animations I made.

.col-sm-8
  = render partial: 'cinemagraphs/forest'
.col-sm-8
  = render partial: 'cinemagraphs/mountain'

app/views/site/show.html.haml
%svg#background
%svg#embroidery
%svg#menu
   %path#menupath1{ fill: 'none', d: "M 60 55 Q 130 25 200 25" } 
   %path#menupath2{ fill: 'none', d: "M 260 35 Q 310 35 380 85" } 